name: Testing c++ only on ubuntu-latest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up requirements & configuration variables
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
          pip install -r build_requirements.txt

      - name: configure
        shell: bash
        run: |
          mkdir build_cxx_only
          cd build_cxx_only
          cmake -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=0' -DCMAKE_BUILD_TYPE=Release ..

      - name: make
        shell: bash
        run: |
          cd build_cxx_only
          make -j4 VERBOSE=1

      - name: install
        shell: bash
        run: |
          cd build_cxx_only
          make install

      - name: configure tests
        shell: bash
        run: |
          mkdir build_cxx_test
          cd build_cxx_test
          cmake -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=0' -DCMAKE_BUILD_TYPE=Release ../tests

      - name: make tests
        shell: bash
        run: |
          cd build_cxx_test
          make -j4 VERBOSE=1

      - name: run tests
        shell: bash
        run: |
          cd build_cxx_test
          make test

      - name: upload test log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: libcasm-mapping-cxx-test-log
          path: build_cxx_test/Testing/Temporary/LastTest.log
